const C=[
{n:"Cloud Strife",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:175,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Gezel Bugenhagen",e:"🔬",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:150,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Dio",e:"🎪",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:195,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Elena",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:160,ha:"Blond",w:"Fäuste",p:"NPC"},
{n:"Heidegger",e:"🎩",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:175,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Marlene Wallace",e:"👧",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:110,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Palmer",e:"🚀",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:180,ha:"Grau",w:"pistole",p:"NPC"},
{n:"Präsident Shinra",e:"👔",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:175,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Reeve Tuesti",e:"🐱",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:178,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Tseng",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:178,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Don Corneo",e:"🎩",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:170,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Rufus Shinra",e:"🕶️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:180,ha:"Blond",w:"Pistole",p:"NPC"},
{n:"Biggs",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:178,ha:"Schwarz",w:"Gewehr",p:"NPC"},
{n:"Wedge",e:"🍔",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:165,ha:"Schwarz",w:"Gewehr",p:"NPC"},
{n:"Jesse",e:"🔧",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:165,ha:"Braun",w:"Gewehr",p:"NPC"},
{n:"Reno",e:"⚡",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:178,ha:"Rosa",w:"Stab",p:"NPC"},
{n:"Rude",e:"🕶️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:190,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Professor Hojo",e:"🧪",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:170,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Scarlet",e:"💄",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:165,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Tifa Lockhart",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:167,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Aerith Gainsborough",e:"🌸",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:163,ha:"Braun",w:"Stab",p:"Spielbar"},
{n:"Sephiroth",e:"🖤",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:195,ha:"Silber",w:"Katana",p:"NPC"},
{n:"Barret Wallace",e:"💪",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:190,ha:"Schwarz",w:"Kanonenarm",p:"Spielbar"},
{n:"Vincent Valentine",e:"🦇",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:182,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Yuffie Kisaragi",e:"🥷",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"weiblich",h:160,ha:"Schwarz",w:"Shuriken",p:"Spielbar"},
{n:"Red XIII",e:"🐺",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:130,ha:"Rot",w:"Fäuste",p:"Spielbar"},
{n:"Cid Highwind",e:"🚬",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ge:"männlich",h:185,ha:"Blond",w:"Speer",p:"Spielbar"},
{n:"Squall Leonheart",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:177,ha:"Braun",w:"Gunblade",p:"Spielbar"},
{n:"Rinoa Heartilly",e:"🌹",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"weiblich",h:163,ha:"Schwarz",w:"Fernkampf",p:"Spielbar"},
{n:"Xell Dincht",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:167,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Quistis Trepe",e:"📚",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"weiblich",h:172,ha:"Blond",w:"Peitsche",p:"Spielbar"},
{n:"Irvine Kinneas",e:"🎯",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:185,ha:"Braun",w:"Scharfschützengewehr",p:"Spielbar"},
{n:"Selphie Tilmitt",e:"🎀",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"weiblich",h:157,ha:"Braun",w:"Nunchaku",p:"Spielbar"},
{n:"Cyfer Almasy",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:188,ha:"Blond",w:"Gunblade",p:"NPC"},
{n:"Laguna Loire",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:161,ha:"Schwarz",w:"Gewehr",p:"Spielbar"},
{n:"Kiros Seagill",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:191,ha:"Braun",w:"Dolch",p:"Spielbar"},
{n:"Ward Zabac",e:"🔱",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:217,ha:"Keine",w:"Harpune",p:"Spielbar"},
{n:"Edea Kramer",e:"🔮",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"weiblich",h:170,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Cid Kramer",e:"🎓",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ge:"männlich",h:172,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Zidane Tribal",e:"🐒",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"männlich",h:176,ha:"Blond",w:"Dolch",p:"Spielbar"},
{n:"Garnet Till Alexandros XVII",e:"👑",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"weiblich",h:158,ha:"Schwarz",w:"Stab",p:"Spielbar"},
{n:"Vivi Orunita",e:"🎩",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"männlich",h:97,ha:"Keine",w:"Stab",p:"Spielbar"},
{n:"Adelbert Steiner",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"männlich",h:181,ha:"Keine",w:"Schwert",p:"Spielbar"},
{n:"Freia Crescent",e:"🐇",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"weiblich",h:155,ha:"Weiß",w:"Speer",p:"Spielbar"},
{n:"Mahagon Coral",e:"🐾",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"männlich",h:190,ha:"Rot",w:"Kralle",p:"Spielbar"},
{n:"Eiko Carol",e:"🌺",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"weiblich",h:108,ha:"Blau",w:"Stab",p:"Spielbar"},
{n:"Quina Quen",e:"🍴",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ge:"männlich",h:179,ha:"Keine",w:"Gabel",p:"Spielbar"},
{n:"Tidus",e:"🏐",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:176,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Seymor Guado",e:"🧙",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:195,ha:"Blau",w:"Magie",p:"NPC"},
{n:"Belgmene",e:"✨",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"weiblich",h:165,ha:"Braun",w:"Magie",p:"NPC"},
{n:"Braska",e:"🙏",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:178,ha:"Grau",w:"Magie",p:"NPC"},
{n:"Cid",e:"✈️",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:180,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Donna",e:"🎭",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"weiblich",h:168,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Isaah",e:"🙏",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:177,ha:"Braun",w:"Magie",p:"NPC"},
{n:"Jekkt",e:"🏈",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:195,ha:"Braun",w:"Schwert",p:"NPC"},
{n:"O'aka XXIII",e:"💰",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:175,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Yuna",e:"🙏",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"weiblich",h:157,ha:"Braun",w:"Stab",p:"Spielbar"},
{n:"Auron",e:"🥃",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:190,ha:"Rot",w:"Schwert",p:"Spielbar"},
{n:"Lulu",e:"🎱",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"weiblich",h:170,ha:"Schwarz",w:"Magie",p:"Spielbar"},
{n:"Wakka",e:"🏉",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"männlich",h:180,ha:"Rot",w:"Fernkampf",p:"Spielbar"},
{n:"Rikku",e:"🔧",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ge:"weiblich",h:155,ha:"Blond",w:"Dolche",p:"Spielbar"},
{n:"Noctis Lucis Caelum",e:"👑",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ge:"männlich",h:175,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Gladiolus Amicitia",e:"💪",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ge:"männlich",h:191,ha:"Schwarz",w:"Großschwert",p:"Spielbar"},
{n:"Ignis Scientia",e:"🔪",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ge:"männlich",h:183,ha:"Braun",w:"Dolche",p:"Spielbar"},
{n:"Prompto Argentum",e:"📸",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ge:"männlich",h:175,ha:"Blond",w:"Pistole",p:"Spielbar"},
{n:"Kratos",e:"⚔️",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure/Hack & Slash",ge:"männlich",h:193,ha:"Keine",w:"Axt",p:"Spielbar"},
{n:"Atreus",e:"🏹",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure/Hack & Slash",ge:"männlich",h:140,ha:"Braun",w:"Bogen",p:"Spielbar"},
{n:"Freya",e:"🔮",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure/Hack & Slash",ge:"weiblich",h:170,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Baldur",e:"💢",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure/Hack & Slash",ge:"männlich",h:185,ha:"Blond",w:"Fäuste",p:"NPC"},
{n:"Zeus",e:"⚡",fr:"God of War",sp:"God of War III",g:"Action-Adventure/Hack & Slash",ge:"männlich",h:180,ha:"Weiß",w:"Magie",p:"NPC"},
{n:"Ares",e:"🔥",fr:"God of War",sp:"God of War III",g:"Action-Adventure/Hack & Slash",ge:"männlich",h:230,ha:"Schwarz",w:"Doppelklingen",p:"NPC"},
{n:"Athena",e:"🦉",fr:"God of War",sp:"God of War III",g:"Action-Adventure/Hack & Slash",ge:"weiblich",h:175,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Tyr",e:"⚖️",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure/Hack & Slash",ge:"männlich",h:195,ha:"Braun",w:"Speer",p:"NPC"},
{n:"Sora",e:"🗝️",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:157,ha:"Braun",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Riku",e:"🌙",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:179,ha:"Silber",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Kairi",e:"🌺",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"weiblich",h:157,ha:"Rot",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Donald Duck",e:"🦆",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:94,ha:"Keine",w:"Magie",p:"Spielbar"},
{n:"Goofy",e:"🐶",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:190,ha:"Keine",w:"Schild",p:"Spielbar"},
{n:"Xemnas",e:"🌑",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:188,ha:"Grau",w:"Energieklinge",p:"NPC"},
{n:"Axel",e:"🔥",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:185,ha:"Rot",w:"Chakram",p:"Spielbar"},
{n:"Roxas",e:"🔑",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ge:"männlich",h:160,ha:"Blond",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Crash Bandicoot",e:"🦊",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ge:"männlich",h:87,ha:"Orange",w:"Fäuste",p:"Spielbar"},
{n:"Coco Bandicoot",e:"💻",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ge:"weiblich",h:132,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Dr. Neo Cortex",e:"🧪",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ge:"männlich",h:180,ha:"Keine",w:"Pistole",p:"NPC"},
{n:"Aku Aku",e:"🎭",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ge:"männlich",h:40,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Crunch Bandicoot",e:"💪",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ge:"männlich",h:210,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Tawna Bandicoot",e:"💃",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ge:"weiblich",h:160,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Mario",e:"🍄",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ge:"männlich",h:155,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Luigi",e:"👻",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ge:"männlich",h:159,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Prinzessin Peach",e:"👑",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ge:"weiblich",h:163,ha:"Blond",w:"Magie",p:"Spielbar"},
{n:"Bowser",e:"🐢",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ge:"männlich",h:244,ha:"Rot",w:"Feueratem",p:"NPC"},
{n:"Yoshi",e:"🦖",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ge:"männlich",h:108,ha:"Keine",w:"Zunge",p:"Spielbar"},
{n:"Toad",e:"🍄",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ge:"männlich",h:120,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Wario",e:"💰",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ge:"männlich",h:175,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Rosalina",e:"✨",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ge:"weiblich",h:180,ha:"Blond",w:"Magie",p:"Spielbar"},
{n:"Donkey Kong",e:"🍌",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ge:"männlich",h:215,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Link",e:"🗡️",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Breath of the Wild",g:"Action-Adventure",ge:"männlich",h:175,ha:"Blond",w:"Schwert & Schild",p:"Spielbar"},
{n:"Prinzessin Zelda",e:"👑",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Breath of the Wild",g:"Action-Adventure",ge:"weiblich",h:163,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Ganondorf",e:"🐗",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Ocarina of Time",g:"Action-Adventure",ge:"männlich",h:226,ha:"Rot",w:"Schwert",p:"NPC"},
{n:"Impa",e:"🥷",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Breath of the Wild",g:"Action-Adventure",ge:"weiblich",h:185,ha:"Weiß",w:"Schwert",p:"NPC"},
{n:"Midna",e:"👑",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Twilight Princess",g:"Action-Adventure",ge:"weiblich",h:60,ha:"Orange",w:"Magie",p:"NPC"},
{n:"Navi",e:"✨",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Ocarina of Time",g:"Action-Adventure",ge:"weiblich",h:10,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Nathan Drake",e:"🏴‍☠️",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ge:"männlich",h:183,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Elena Fisher",e:"📷",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ge:"weiblich",h:170,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Victor Sullivan",e:"🚬",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ge:"männlich",h:178,ha:"Grau",w:"Pistole",p:"NPC"},
{n:"Chloe Frazer",e:"🗝️",fr:"Uncharted",sp:"Uncharted: The Lost Legacy",g:"Action-Adventure",ge:"weiblich",h:168,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Sam Drake",e:"🎲",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ge:"männlich",h:185,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Lara Croft",e:"🏹",fr:"Tomb Raider",sp:"Shadow of the Tomb Raider",g:"Action-Adventure",ge:"weiblich",h:173,ha:"Braun",w:"Bogen",p:"Spielbar"},
{n:"Jonah Maiava",e:"⚓",fr:"Tomb Raider",sp:"Shadow of the Tomb Raider",g:"Action-Adventure",ge:"männlich",h:190,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Winston",e:"🧑‍💼",fr:"Tomb Raider",sp:"Shadow of the Tomb Raider",g:"Action-Adventure",ge:"männlich",h:175,ha:"Weiß",w:"Keine",p:"NPC"},
{n:"Gustave",e:"🔧",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ge:"männlich",h:180,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Maelle",e:"⚔️",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ge:"weiblich",h:165,ha:"Weiß",w:"Degen",p:"Spielbar"},
{n:"Lune",e:"📖",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ge:"weiblich",h:170,ha:"Blau",w:"Magie",p:"Spielbar"},
{n:"Sciel",e:"🃏",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ge:"weiblich",h:172,ha:"Schwarz",w:"Sense",p:"Spielbar"},
{n:"Verso",e:"🎹",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ge:"männlich",h:178,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Monoco",e:"🎭",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ge:"männlich",h:190,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Solaire of Astora",e:"☀️",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ge:"männlich",h:185,ha:"Blond",w:"Großschwert",p:"NPC"},
{n:"Gwyn, Lord of Cinder",e:"🔥",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ge:"männlich",h:200,ha:"Grau",w:"Großschwert",p:"NPC"},
{n:"Artorias the Abysswalker",e:"🐺",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ge:"männlich",h:195,ha:"Schwarz",w:"Großschwert",p:"NPC"},
{n:"Siegmeyer of Catarina",e:"🥚",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ge:"männlich",h:195,ha:"Blond",w:"Zweihänder",p:"NPC"},
{n:"Priscilla, Crossbreed",e:"🦋",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ge:"weiblich",h:190,ha:"Weiß",w:"Schwert",p:"NPC"},
{n:"Melina",e:"🌙",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ge:"weiblich",h:165,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Malenia, Blade of Miquella",e:"🌸",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ge:"weiblich",h:178,ha:"Rosa",w:"Katana",p:"NPC"},
{n:"Starscourge Radahn",e:"☀️",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ge:"männlich",h:250,ha:"Rot",w:"Doppelschwerter",p:"NPC"},
{n:"Ranni the Witch",e:"🌌",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ge:"weiblich",h:150,ha:"Silber",w:"Magie",p:"NPC"},
{n:"Godrick the Grafted",e:"🦴",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ge:"männlich",h:280,ha:"Grau",w:"Axt",p:"NPC"},
{n:"Millicent",e:"🌹",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ge:"weiblich",h:170,ha:"Rot",w:"Dolch",p:"NPC"},
{n:"Jonesy",e:"🕵️",fr:"Fortnite",sp:"Fortnite",g:"Battle Royale",ge:"männlich",h:180,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Peely",e:"🍌",fr:"Fortnite",sp:"Fortnite",g:"Battle Royale",ge:"männlich",h:175,ha:"Keine",w:"Gewehr",p:"Spielbar"},
{n:"Midas",e:"👑",fr:"Fortnite",sp:"Fortnite",g:"Battle Royale",ge:"männlich",h:185,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Meowscles",e:"🐱",fr:"Fortnite",sp:"Fortnite",g:"Battle Royale",ge:"männlich",h:190,ha:"Weiß",w:"Gewehr",p:"Spielbar"},
{n:"The Foundation",e:"🗿",fr:"Fortnite",sp:"Fortnite",g:"Battle Royale",ge:"männlich",h:200,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Leon S. Kennedy",e:"🚔",fr:"Resident Evil",sp:"Resident Evil 4",g:"Survival Horror",ge:"männlich",h:183,ha:"Blond",w:"Pistole",p:"Spielbar"},
{n:"Jill Valentine",e:"🌟",fr:"Resident Evil",sp:"Resident Evil 3",g:"Survival Horror",ge:"weiblich",h:170,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Chris Redfield",e:"💪",fr:"Resident Evil",sp:"Resident Evil 5",g:"Survival Horror",ge:"männlich",h:185,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Ada Wong",e:"🔴",fr:"Resident Evil",sp:"Resident Evil 4",g:"Survival Horror",ge:"weiblich",h:168,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Albert Wesker",e:"🕶️",fr:"Resident Evil",sp:"Resident Evil 5",g:"Survival Horror",ge:"männlich",h:186,ha:"Blond",w:"Pistole",p:"NPC"},
{n:"Claire Redfield",e:"🏍️",fr:"Resident Evil",sp:"Resident Evil 2",g:"Survival Horror",ge:"weiblich",h:168,ha:"Rot",w:"Pistole",p:"Spielbar"},
{n:"Solid Snake",e:"🚬",fr:"Metal Gear Solid",sp:"Metal Gear Solid",g:"Stealth-Action",ge:"männlich",h:178,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Big Boss",e:"🎖️",fr:"Metal Gear Solid",sp:"Metal Gear Solid V: The Phantom Pain",g:"Stealth-Action",ge:"männlich",h:182,ha:"Schwarz",w:"Gewehr",p:"Spielbar"},
{n:"Raiden",e:"⚡",fr:"Metal Gear Solid",sp:"Metal Gear Solid 2: Sons of Liberty",g:"Stealth-Action",ge:"männlich",h:182,ha:"Blond",w:"Katana",p:"Spielbar"},
{n:"Revolver Ocelot",e:"🤠",fr:"Metal Gear Solid",sp:"Metal Gear Solid V: The Phantom Pain",g:"Stealth-Action",ge:"männlich",h:180,ha:"Weiß",w:"Revolver",p:"NPC"},
{n:"Liquid Snake",e:"🐍",fr:"Metal Gear Solid",sp:"Metal Gear Solid",g:"Stealth-Action",ge:"männlich",h:180,ha:"Blond",w:"Gewehr",p:"NPC"},
{n:"Ryu",e:"🥋",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ge:"männlich",h:175,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Ken Masters",e:"🔥",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ge:"männlich",h:175,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Chun-Li",e:"🦵",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ge:"weiblich",h:165,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Guile",e:"🇺🇸",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ge:"männlich",h:182,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"M. Bison",e:"👊",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ge:"männlich",h:188,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Akuma",e:"👹",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ge:"männlich",h:187,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Scorpion",e:"🔥",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ge:"männlich",h:188,ha:"Schwarz",w:"Speer",p:"Spielbar"},
{n:"Sub-Zero",e:"❄️",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ge:"männlich",h:185,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Liu Kang",e:"🐉",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ge:"männlich",h:180,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Raiden (Mortal Kombat)",e:"⚡",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ge:"männlich",h:180,ha:"Weiß",w:"Magie",p:"NPC"},
{n:"Sonya Blade",e:"💥",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ge:"weiblich",h:170,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Master Chief",e:"🪖",fr:"Halo",sp:"Halo: Combat Evolved",g:"FPS",ge:"männlich",h:213,ha:"Keine",w:"Gewehr",p:"Spielbar"},
{n:"Cortana",e:"💠",fr:"Halo",sp:"Halo: Combat Evolved",g:"FPS",ge:"weiblich",h:170,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Arbiter",e:"👽",fr:"Halo",sp:"Halo 2",g:"FPS",ge:"männlich",h:230,ha:"Keine",w:"Energieklinge",p:"Spielbar"},
{n:"Geralt of Rivia",e:"⚔️",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ge:"männlich",h:181,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Yennefer of Vengerberg",e:"🔮",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ge:"weiblich",h:160,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Triss Merigold",e:"🔥",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ge:"weiblich",h:168,ha:"Rot",w:"Magie",p:"NPC"},
{n:"Ciri",e:"⚔️",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ge:"weiblich",h:172,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Aloy",e:"🏹",fr:"Horizon",sp:"Horizon Zero Dawn",g:"Action-RPG",ge:"weiblich",h:173,ha:"Rot",w:"Bogen",p:"Spielbar"},
{n:"Rost",e:"🏹",fr:"Horizon",sp:"Horizon Zero Dawn",g:"Action-RPG",ge:"männlich",h:185,ha:"Braun",w:"Bogen",p:"NPC"},
{n:"Sylens",e:"🎭",fr:"Horizon",sp:"Horizon Zero Dawn",g:"Action-RPG",ge:"männlich",h:180,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Wolf",e:"🥷",fr:"Sekiro",sp:"Sekiro: Shadows Die Twice",g:"Souls-like",ge:"männlich",h:175,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Genichiro Ashina",e:"⚡",fr:"Sekiro",sp:"Sekiro: Shadows Die Twice",g:"Souls-like",ge:"männlich",h:180,ha:"Schwarz",w:"Katana",p:"NPC"},
{n:"Der Jäger",e:"🌙",fr:"Bloodborne",sp:"Bloodborne",g:"Souls-like",ge:"männlich",h:180,ha:"Schwarz",w:"Sense",p:"Spielbar"},
{n:"Gehrman",e:"🕯️",fr:"Bloodborne",sp:"Bloodborne",g:"Souls-like",ge:"männlich",h:185,ha:"Grau",w:"Sense",p:"NPC"},
{n:"Lady Maria",e:"🗡️",fr:"Bloodborne",sp:"Bloodborne",g:"Souls-like",ge:"weiblich",h:170,ha:"Weiß",w:"Zwei Schwerter",p:"NPC"},
{n:"Joker",e:"🎭",fr:"Persona",sp:"Persona 5",g:"JRPG",ge:"männlich",h:174,ha:"Schwarz",w:"Dolch",p:"Spielbar"},
{n:"Morgana",e:"🐱",fr:"Persona",sp:"Persona 5",g:"JRPG",ge:"männlich",h:50,ha:"Schwarz",w:"Dolch",p:"Spielbar"},
{n:"Ann Takamaki",e:"👠",fr:"Persona",sp:"Persona 5",g:"JRPG",ge:"weiblich",h:160,ha:"Blond",w:"Peitsche",p:"Spielbar"},
{n:"Ryuji Sakamoto",e:"⚡",fr:"Persona",sp:"Persona 5",g:"JRPG",ge:"männlich",h:172,ha:"Blond",w:"Keule",p:"Spielbar"},
{n:"Dante",e:"😈",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ge:"männlich",h:189,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Vergil",e:"⚔️",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ge:"männlich",h:186,ha:"Weiß",w:"Katana",p:"NPC"},
{n:"Nero",e:"🦾",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ge:"männlich",h:180,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Trish",e:"⚡",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ge:"weiblich",h:175,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Tracer",e:"⏱️",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ge:"weiblich",h:163,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Reaper",e:"💀",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ge:"männlich",h:195,ha:"Schwarz",w:"Schrotflinte",p:"Spielbar"},
{n:"Widowmaker",e:"🎯",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ge:"weiblich",h:180,ha:"Schwarz",w:"Scharfschützengewehr",p:"Spielbar"},
{n:"D.Va",e:"🎮",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ge:"weiblich",h:158,ha:"Braun",w:"Mech-Kanonen",p:"Spielbar"},
{n:"Genji",e:"🍃",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ge:"männlich",h:175,ha:"Braun",w:"Katana",p:"Spielbar"},
{n:"Steve",e:"⛏️",fr:"Minecraft",sp:"Minecraft",g:"Sandbox",ge:"männlich",h:180,ha:"Braun",w:"Spitzhacke",p:"Spielbar"},
{n:"Alex",e:"🏹",fr:"Minecraft",sp:"Minecraft",g:"Sandbox",ge:"weiblich",h:180,ha:"Rot",w:"Bogen",p:"Spielbar"},
{n:"Enderman",e:"🕶️",fr:"Minecraft",sp:"Minecraft",g:"Sandbox",ge:"männlich",h:290,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Creeper",e:"💚",fr:"Minecraft",sp:"Minecraft",g:"Sandbox",ge:"männlich",h:180,ha:"Keine",w:"Explosion",p:"NPC"},
{n:"Carl \"CJ\" Johnson",e:"🎮",fr:"Grand Theft Auto",sp:"Grand Theft Auto: San Andreas",g:"Open World",ge:"männlich",h:183,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Trevor Philips",e:"🔫",fr:"Grand Theft Auto",sp:"Grand Theft Auto V",g:"Open World",ge:"männlich",h:178,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Michael De Santa",e:"🕶️",fr:"Grand Theft Auto",sp:"Grand Theft Auto V",g:"Open World",ge:"männlich",h:180,ha:"Grau",w:"Pistole",p:"Spielbar"},
{n:"Franklin Clinton",e:"🎧",fr:"Grand Theft Auto",sp:"Grand Theft Auto V",g:"Open World",ge:"männlich",h:180,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Peter Parker",e:"🕷️",fr:"Marvel's Spider-Man",sp:"Marvel's Spider-Man",g:"Action-Adventure",ge:"männlich",h:178,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Miles Morales",e:"🕸️",fr:"Marvel's Spider-Man",sp:"Marvel's Spider-Man: Miles Morales",g:"Action-Adventure",ge:"männlich",h:175,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Mary Jane Watson",e:"📰",fr:"Marvel's Spider-Man",sp:"Marvel's Spider-Man",g:"Action-Adventure",ge:"weiblich",h:168,ha:"Rot",w:"Keine",p:"NPC"},
{n:"Ezio Auditore",e:"🗡️",fr:"Assassin's Creed",sp:"Assassin's Creed II",g:"Action-Adventure/Stealth-Action",ge:"männlich",h:178,ha:"Braun",w:"Versteckte Klinge",p:"Spielbar"},
{n:"Altaïr Ibn-La'Ahad",e:"🦅",fr:"Assassin's Creed",sp:"Assassin's Creed",g:"Action-Adventure/Stealth-Action",ge:"männlich",h:180,ha:"Schwarz",w:"Versteckte Klinge",p:"Spielbar"},
{n:"Connor Kenway",e:"🏹",fr:"Assassin's Creed",sp:"Assassin's Creed III",g:"Action-Adventure/Stealth-Action",ge:"männlich",h:188,ha:"Schwarz",w:"Tomahawk",p:"Spielbar"},
{n:"Kassandra",e:"⚔️",fr:"Assassin's Creed",sp:"Assassin's Creed Odyssey",g:"Action-Adventure/Stealth-Action",ge:"weiblich",h:178,ha:"Schwarz",w:"Speer",p:"Spielbar"},
{n:"V",e:"🤖",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG/FPS",ge:"männlich",h:175,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Johnny Silverhand",e:"🎸",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG/FPS",ge:"männlich",h:183,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Judy Alvarez",e:"🥽",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG/FPS",ge:"weiblich",h:163,ha:"Blau",w:"Pistole",p:"NPC"},
{n:"Panam Palmer",e:"🚗",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG/FPS",ge:"weiblich",h:165,ha:"Braun",w:"Gewehr",p:"NPC"},
{n:"Joel Miller",e:"🎸",fr:"The Last of Us",sp:"The Last of Us",g:"Survival Horror/Action-Adventure",ge:"männlich",h:188,ha:"Grau",w:"Gewehr",p:"Spielbar"},
{n:"Ellie Williams",e:"🔪",fr:"The Last of Us",sp:"The Last of Us",g:"Survival Horror/Action-Adventure",ge:"weiblich",h:163,ha:"Braun",w:"Messer",p:"Spielbar"},
{n:"Abby Anderson",e:"💪",fr:"The Last of Us",sp:"The Last of Us Part II",g:"Survival Horror/Action-Adventure",ge:"weiblich",h:178,ha:"Blond",w:"Gewehr",p:"Spielbar"},
{n:"Bayonetta",e:"💃",fr:"Bayonetta",sp:"Bayonetta",g:"Hack & Slash",ge:"weiblich",h:172,ha:"Schwarz",w:"Pistolen",p:"Spielbar"},
{n:"Jeanne",e:"🕶️",fr:"Bayonetta",sp:"Bayonetta",g:"Hack & Slash",ge:"weiblich",h:172,ha:"Blond",w:"Pistolen",p:"NPC"},
{n:"Sonic the Hedgehog",e:"💨",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ge:"männlich",h:100,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Tails",e:"🦊",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ge:"männlich",h:80,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Knuckles the Echidna",e:"👊",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ge:"männlich",h:107,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Dr. Eggman",e:"🥚",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ge:"männlich",h:185,ha:"Keine",w:"Maschinen",p:"NPC"},
{n:"Shadow the Hedgehog",e:"🖤",fr:"Sonic the Hedgehog",sp:"Sonic Adventure 2",g:"Platformer",ge:"männlich",h:100,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Amy Rose",e:"🔨",fr:"Sonic the Hedgehog",sp:"Sonic CD",g:"Platformer",ge:"weiblich",h:90,ha:"Keine",w:"Hammer",p:"Spielbar"},
{n:"Mega Man",e:"🤖",fr:"Mega Man",sp:"Mega Man 2",g:"Platformer",ge:"männlich",h:130,ha:"Keine",w:"Blaster",p:"Spielbar"},
{n:"Dr. Wily",e:"🧪",fr:"Mega Man",sp:"Mega Man 2",g:"Platformer",ge:"männlich",h:170,ha:"Weiß",w:"Maschinen",p:"NPC"},
{n:"Roll",e:"🧹",fr:"Mega Man",sp:"Mega Man 2",g:"Platformer",ge:"weiblich",h:125,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Samus Aran",e:"🚀",fr:"Metroid",sp:"Super Metroid",g:"Metroidvania",ge:"weiblich",h:185,ha:"Blond",w:"Blaster",p:"Spielbar"},
{n:"Deckard Cain",e:"📚",fr:"Diablo",sp:"Diablo II",g:"Action-RPG/Hack & Slash",ge:"männlich",h:175,ha:"Weiß",w:"Stab",p:"NPC"},
{n:"Lilith",e:"😈",fr:"Diablo",sp:"Diablo IV",g:"Action-RPG/Hack & Slash",ge:"weiblich",h:180,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Arthur Morgan",e:"🤠",fr:"Red Dead Redemption",sp:"Red Dead Redemption 2",g:"Open World",ge:"männlich",h:183,ha:"Braun",w:"Revolver",p:"Spielbar"},
{n:"John Marston",e:"🐴",fr:"Red Dead Redemption",sp:"Red Dead Redemption",g:"Open World",ge:"männlich",h:180,ha:"Braun",w:"Revolver",p:"Spielbar"},
{n:"Dutch van der Linde",e:"🎩",fr:"Red Dead Redemption",sp:"Red Dead Redemption 2",g:"Open World",ge:"männlich",h:178,ha:"Braun",w:"Revolver",p:"NPC"},
{n:"Cuphead",e:"☕",fr:"Cuphead",sp:"Cuphead",g:"Platformer",ge:"männlich",h:90,ha:"Keine",w:"Finger-Pistole",p:"Spielbar"},
{n:"Mugman",e:"🍶",fr:"Cuphead",sp:"Cuphead",g:"Platformer",ge:"männlich",h:90,ha:"Keine",w:"Finger-Pistole",p:"Spielbar"},
{n:"King Dice",e:"🎲",fr:"Cuphead",sp:"Cuphead",g:"Platformer",ge:"männlich",h:175,ha:"Keine",w:"Magie",p:"NPC"},
{n:"The Knight",e:"🗡️",fr:"Hollow Knight",sp:"Hollow Knight",g:"Metroidvania",ge:"männlich",h:60,ha:"Keine",w:"Nagel",p:"Spielbar"},
{n:"Hornet",e:"🕷️",fr:"Hollow Knight",sp:"Hollow Knight",g:"Metroidvania",ge:"weiblich",h:65,ha:"Keine",w:"Nadel",p:"Spielbar"},
{n:"Doom Slayer",e:"😈",fr:"Doom",sp:"Doom Eternal",g:"FPS",ge:"männlich",h:205,ha:"Keine",w:"Gewehr",p:"Spielbar"},
{n:"Ahri",e:"🦊",fr:"League of Legends",sp:"League of Legends",g:"MOBA",ge:"weiblich",h:163,ha:"Orange",w:"Magie",p:"Spielbar"},
{n:"Yasuo",e:"⚔️",fr:"League of Legends",sp:"League of Legends",g:"MOBA",ge:"männlich",h:183,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Jinx",e:"💥",fr:"League of Legends",sp:"League of Legends",g:"MOBA",ge:"weiblich",h:175,ha:"Blau",w:"Gewehr",p:"Spielbar"},
{n:"Lux",e:"✨",fr:"League of Legends",sp:"League of Legends",g:"MOBA",ge:"weiblich",h:169,ha:"Blond",w:"Magie",p:"Spielbar"},
{n:"Garen",e:"⚔️",fr:"League of Legends",sp:"League of Legends",g:"MOBA",ge:"männlich",h:193,ha:"Blond",w:"Großschwert",p:"Spielbar"}
];
