const C=[
{n:"Cloud Strife",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Gezel Bugenhagen",e:"🔬",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:150,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Dio",e:"🎪",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:195,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Elena",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:160,ha:"Blond",w:"Fäuste",p:"NPC"},
{n:"Heidegger",e:"🎩",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Marlene Wallace",e:"👧",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:110,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Palmer",e:"🚀",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Grau",w:"pistole",p:"NPC"},
{n:"Präsident Shinra",e:"👔",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Reeve Tuesti",e:"🐱",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Tseng",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Don Corneo",e:"🎩",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:170,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Rufus Shinra",e:"🕶️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Blond",w:"Pistole",p:"NPC"},
{n:"Biggs",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Gewehr",p:"NPC"},
{n:"Wedge",e:"🍔",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:165,ha:"Schwarz",w:"Gewehr",p:"NPC"},
{n:"Jesse",e:"🔧",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Braun",w:"Gewehr",p:"NPC"},
{n:"Reno",e:"⚡",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Rosa",w:"Stab",p:"NPC"},
{n:"Rude",e:"🕶️",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:190,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Professor Hojo",e:"🧪",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:170,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Scarlet",e:"💄",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Tifa Lockhart",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:167,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Aerith Gainsborough",e:"🌸",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:163,ha:"Braun",w:"Stab",p:"Spielbar"},
{n:"Sephiroth",e:"🖤",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:195,ha:"Silber",w:"Katana",p:"NPC"},
{n:"Barret Wallace",e:"💪",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:190,ha:"Schwarz",w:"Kanonenarm",p:"Spielbar"},
{n:"Vincent Valentine",e:"🦇",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:182,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Yuffie Kisaragi",e:"🥷",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:160,ha:"Schwarz",w:"Shuriken",p:"Spielbar"},
{n:"Red XIII",e:"🐺",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Tier",ge:"männlich",h:130,ha:"Rot",w:"Fäuste",p:"Spielbar"},
{n:"Cid Highwind",e:"🚬",fr:"Final Fantasy",sp:"Final Fantasy VII",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Blond",w:"Speer",p:"Spielbar"},
{n:"Squall Leonheart",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:177,ha:"Braun",w:"Gunblade",p:"Spielbar"},
{n:"Rinoa Heartilly",e:"🌹",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:163,ha:"Schwarz",w:"Fernkampf",p:"Spielbar"},
{n:"Xell Dincht",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:167,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Quistis Trepe",e:"📚",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:172,ha:"Blond",w:"Peitsche",p:"Spielbar"},
{n:"Irvine Kinneas",e:"🎯",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Scharfschützengewehr",p:"Spielbar"},
{n:"Selphie Tilmitt",e:"🎀",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:157,ha:"Braun",w:"Nunchaku",p:"Spielbar"},
{n:"Cyfer Almasy",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:188,ha:"Blond",w:"Gunblade",p:"NPC"},
{n:"Laguna Loire",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:161,ha:"Schwarz",w:"Gewehr",p:"Spielbar"},
{n:"Kiros Seagill",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:191,ha:"Braun",w:"Dolch",p:"Spielbar"},
{n:"Ward Zabac",e:"🔱",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:217,ha:"Keine",w:"Harpune",p:"Spielbar"},
{n:"Edea Kramer",e:"🔮",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:170,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Cid Kramer",e:"🎓",fr:"Final Fantasy",sp:"Final Fantasy VIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:172,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Zidane Tribal",e:"🐒",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Mensch",ge:"männlich",h:176,ha:"Blond",w:"Dolch",p:"Spielbar"},
{n:"Garnet Till Alexandros XVII",e:"👑",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Mensch",ge:"weiblich",h:158,ha:"Schwarz",w:"Stab",p:"Spielbar"},
{n:"Vivi Orunita",e:"🎩",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Magisches Wesen",ge:"männlich",h:97,ha:"Keine",w:"Stab",p:"Spielbar"},
{n:"Adelbert Steiner",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Mensch",ge:"männlich",h:181,ha:"Keine",w:"Schwert",p:"Spielbar"},
{n:"Freia Crescent",e:"🐇",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Tier",ge:"weiblich",h:155,ha:"Weiß",w:"Speer",p:"Spielbar"},
{n:"Mahagon Coral",e:"🐾",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Mensch",ge:"männlich",h:190,ha:"Rot",w:"Kralle",p:"Spielbar"},
{n:"Eiko Carol",e:"🌺",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Mensch",ge:"weiblich",h:108,ha:"Blau",w:"Stab",p:"Spielbar"},
{n:"Quina Quen",e:"🍴",fr:"Final Fantasy",sp:"Final Fantasy IX",g:"JRPG",ra:"Tier",ge:"männlich",h:179,ha:"Keine",w:"Gabel",p:"Spielbar"},
{n:"Tidus",e:"🏐",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:176,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Seymor Guado",e:"🧙",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:195,ha:"Blau",w:"Magie",p:"NPC"},
{n:"Belgmene",e:"✨",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Braun",w:"Magie",p:"NPC"},
{n:"Braska",e:"🙏",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Grau",w:"Magie",p:"NPC"},
{n:"Cid",e:"✈️",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Donna",e:"🎭",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"weiblich",h:168,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Isaah",e:"🙏",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:177,ha:"Braun",w:"Magie",p:"NPC"},
{n:"Jekkt",e:"🏈",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:195,ha:"Braun",w:"Schwert",p:"NPC"},
{n:"O'aka XXIII",e:"💰",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Yuna",e:"🙏",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"weiblich",h:157,ha:"Braun",w:"Stab",p:"Spielbar"},
{n:"Auron",e:"🥃",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:190,ha:"Rot",w:"Schwert",p:"Spielbar"},
{n:"Lulu",e:"🎱",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"weiblich",h:170,ha:"Schwarz",w:"Magie",p:"Spielbar"},
{n:"Wakka",e:"🏉",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Rot",w:"Fernkampf",p:"Spielbar"},
{n:"Rikku",e:"🔧",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Mensch",ge:"weiblich",h:155,ha:"Blond",w:"Dolche",p:"Spielbar"},
{n:"Noctis Lucis Caelum",e:"👑",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Gladiolus Amicitia",e:"💪",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ra:"Mensch",ge:"männlich",h:191,ha:"Schwarz",w:"Großschwert",p:"Spielbar"},
{n:"Ignis Scientia",e:"🔪",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ra:"Mensch",ge:"männlich",h:183,ha:"Braun",w:"Dolche",p:"Spielbar"},
{n:"Prompto Argentum",e:"📸",fr:"Final Fantasy",sp:"Final Fantasy XV",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Blond",w:"Pistole",p:"Spielbar"},
{n:"Kratos",e:"⚔️",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure",ra:"Halbgott",ge:"männlich",h:193,ha:"Keine",w:"Axt",p:"Spielbar"},
{n:"Atreus",e:"🏹",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure",ra:"Halbgott",ge:"männlich",h:140,ha:"Braun",w:"Bogen",p:"Spielbar"},
{n:"Freya",e:"🔮",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure",ra:"Gott",ge:"weiblich",h:170,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Baldur",e:"💢",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure",ra:"Gott",ge:"männlich",h:185,ha:"Blond",w:"Fäuste",p:"NPC"},
{n:"Zeus",e:"⚡",fr:"God of War",sp:"God of War III",g:"Action-Adventure",ra:"Gott",ge:"männlich",h:180,ha:"Weiß",w:"Magie",p:"NPC"},
{n:"Ares",e:"🔥",fr:"God of War",sp:"God of War III",g:"Action-Adventure",ra:"Gott",ge:"männlich",h:230,ha:"Schwarz",w:"Doppelklingen",p:"NPC"},
{n:"Athena",e:"🦉",fr:"God of War",sp:"God of War III",g:"Action-Adventure",ra:"Gott",ge:"weiblich",h:175,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Tyr",e:"⚖️",fr:"God of War",sp:"God of War (2018)",g:"Action-Adventure",ra:"Gott",ge:"männlich",h:195,ha:"Braun",w:"Speer",p:"NPC"},
{n:"Sora",e:"🗝️",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:157,ha:"Braun",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Riku",e:"🌙",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:179,ha:"Silber",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Kairi",e:"🌺",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:157,ha:"Rot",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Donald Duck",e:"🦆",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Tier",ge:"männlich",h:94,ha:"Keine",w:"Magie",p:"Spielbar"},
{n:"Goofy",e:"🐶",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Tier",ge:"männlich",h:190,ha:"Keine",w:"Schild",p:"Spielbar"},
{n:"Xemnas",e:"🌑",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Untoter",ge:"männlich",h:188,ha:"Grau",w:"Energieklinge",p:"NPC"},
{n:"Axel",e:"🔥",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Untoter",ge:"männlich",h:185,ha:"Rot",w:"Chakram",p:"Spielbar"},
{n:"Roxas",e:"🔑",fr:"Kingdom Hearts",sp:"Kingdom Hearts III",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:160,ha:"Blond",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Crash Bandicoot",e:"🦊",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ra:"Tier",ge:"männlich",h:87,ha:"Orange",w:"Fäuste",p:"Spielbar"},
{n:"Coco Bandicoot",e:"💻",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ra:"Tier",ge:"weiblich",h:132,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Dr. Neo Cortex",e:"🧪",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ra:"Mensch",ge:"männlich",h:180,ha:"Keine",w:"Pistole",p:"NPC"},
{n:"Aku Aku",e:"🎭",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ra:"Geist",ge:"männlich",h:40,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Crunch Bandicoot",e:"💪",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ra:"Tier",ge:"männlich",h:210,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Tawna Bandicoot",e:"💃",fr:"Crash Bandicoot",sp:"Crash Bandicoot 4: It's About Time",g:"Platformer",ra:"Tier",ge:"weiblich",h:160,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Mario",e:"🍄",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ra:"Mensch",ge:"männlich",h:155,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Luigi",e:"👻",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ra:"Mensch",ge:"männlich",h:159,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Prinzessin Peach",e:"👑",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ra:"Mensch",ge:"weiblich",h:163,ha:"Blond",w:"Magie",p:"Spielbar"},
{n:"Bowser",e:"🐢",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ra:"Monster",ge:"männlich",h:244,ha:"Rot",w:"Feueratem",p:"NPC"},
{n:"Yoshi",e:"🦖",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ra:"Tier",ge:"männlich",h:108,ha:"Keine",w:"Zunge",p:"Spielbar"},
{n:"Toad",e:"🍄",fr:"Super Mario",sp:"Super Mario Odyssey",g:"Platformer",ra:"Magisches Wesen",ge:"männlich",h:120,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Wario",e:"💰",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Rosalina",e:"✨",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ra:"Mensch",ge:"weiblich",h:180,ha:"Blond",w:"Magie",p:"Spielbar"},
{n:"Donkey Kong",e:"🍌",fr:"Super Mario",sp:"Super Mario Party",g:"Platformer",ra:"Tier",ge:"männlich",h:215,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Link",e:"🗡️",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Breath of the Wild",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:175,ha:"Blond",w:"Schwert & Schild",p:"Spielbar"},
{n:"Prinzessin Zelda",e:"👑",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Breath of the Wild",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:163,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Ganondorf",e:"🐗",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Ocarina of Time",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:226,ha:"Rot",w:"Schwert",p:"NPC"},
{n:"Impa",e:"🥷",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Breath of the Wild",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:185,ha:"Weiß",w:"Schwert",p:"NPC"},
{n:"Midna",e:"👑",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Twilight Princess",g:"Action-Adventure",ra:"Magisches Wesen",ge:"weiblich",h:60,ha:"Orange",w:"Magie",p:"NPC"},
{n:"Navi",e:"✨",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Ocarina of Time",g:"Action-Adventure",ra:"Fee",ge:"weiblich",h:10,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Nathan Drake",e:"🏴‍☠️",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:183,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Elena Fisher",e:"📷",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:170,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Victor Sullivan",e:"🚬",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Grau",w:"Pistole",p:"NPC"},
{n:"Chloe Frazer",e:"🗝️",fr:"Uncharted",sp:"Uncharted: The Lost Legacy",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:168,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Sam Drake",e:"🎲",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Lara Croft",e:"🏹",fr:"Tomb Raider",sp:"Shadow of the Tomb Raider",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:173,ha:"Braun",w:"Bogen",p:"Spielbar"},
{n:"Jonah Maiava",e:"⚓",fr:"Tomb Raider",sp:"Shadow of the Tomb Raider",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:190,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Winston",e:"🧑‍💼",fr:"Tomb Raider",sp:"Shadow of the Tomb Raider",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:175,ha:"Weiß",w:"Keine",p:"NPC"},
{n:"Gustave",e:"🔧",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Maelle",e:"⚔️",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Weiß",w:"Degen",p:"Spielbar"},
{n:"Lune",e:"📖",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ra:"Mensch",ge:"weiblich",h:170,ha:"Blau",w:"Magie",p:"Spielbar"},
{n:"Sciel",e:"🃏",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ra:"Mensch",ge:"weiblich",h:172,ha:"Schwarz",w:"Sense",p:"Spielbar"},
{n:"Verso",e:"🎹",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Monoco",e:"🎭",fr:"Clair Obscur: Expedition 33",sp:"Clair Obscur: Expedition 33",g:"JRPG",ra:"Monster",ge:"männlich",h:190,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Solaire of Astora",e:"☀️",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Mensch",ge:"männlich",h:185,ha:"Blond",w:"Großschwert",p:"NPC"},
{n:"Gwyn, Lord of Cinder",e:"🔥",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Gott",ge:"männlich",h:200,ha:"Grau",w:"Großschwert",p:"NPC"},
{n:"Artorias the Abysswalker",e:"🐺",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Mensch",ge:"männlich",h:195,ha:"Schwarz",w:"Großschwert",p:"NPC"},
{n:"Siegmeyer of Catarina",e:"🥚",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Mensch",ge:"männlich",h:195,ha:"Blond",w:"Zweihänder",p:"NPC"},
{n:"Priscilla, Crossbreed",e:"🦋",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Drache",ge:"weiblich",h:190,ha:"Weiß",w:"Schwert",p:"NPC"},
{n:"Melina",e:"🌙",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Geist",ge:"weiblich",h:165,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Malenia, Blade of Miquella",e:"🌸",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"weiblich",h:178,ha:"Rosa",w:"Katana",p:"NPC"},
{n:"Starscourge Radahn",e:"☀️",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:250,ha:"Rot",w:"Doppelschwerter",p:"NPC"},
{n:"Ranni the Witch",e:"🌌",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"weiblich",h:150,ha:"Silber",w:"Magie",p:"NPC"},
{n:"Godrick the Grafted",e:"🦴",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:280,ha:"Grau",w:"Axt",p:"NPC"},
{n:"Millicent",e:"🌹",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Mensch",ge:"weiblich",h:170,ha:"Rot",w:"Dolch",p:"NPC"},
{n:"Jonesy",e:"🕵️",fr:"Fortnite",sp:"Fortnite",g:"FPS",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Peely",e:"🍌",fr:"Fortnite",sp:"Fortnite",g:"FPS",ra:"Magisches Wesen",ge:"männlich",h:175,ha:"Keine",w:"Gewehr",p:"Spielbar"},
{n:"Midas",e:"👑",fr:"Fortnite",sp:"Fortnite",g:"FPS",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Meowscles",e:"🐱",fr:"Fortnite",sp:"Fortnite",g:"FPS",ra:"Tier",ge:"männlich",h:190,ha:"Weiß",w:"Gewehr",p:"Spielbar"},
{n:"The Foundation",e:"🗿",fr:"Fortnite",sp:"Fortnite",g:"FPS",ra:"Mensch",ge:"männlich",h:200,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Leon S. Kennedy",e:"🚔",fr:"Resident Evil",sp:"Resident Evil 4",g:"Survival Horror",ra:"Mensch",ge:"männlich",h:183,ha:"Blond",w:"Pistole",p:"Spielbar"},
{n:"Jill Valentine",e:"🌟",fr:"Resident Evil",sp:"Resident Evil 3",g:"Survival Horror",ra:"Mensch",ge:"weiblich",h:170,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Chris Redfield",e:"💪",fr:"Resident Evil",sp:"Resident Evil 5",g:"Survival Horror",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Ada Wong",e:"🔴",fr:"Resident Evil",sp:"Resident Evil 4",g:"Survival Horror",ra:"Mensch",ge:"weiblich",h:168,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Albert Wesker",e:"🕶️",fr:"Resident Evil",sp:"Resident Evil 5",g:"Survival Horror",ra:"Mensch",ge:"männlich",h:186,ha:"Blond",w:"Pistole",p:"NPC"},
{n:"Claire Redfield",e:"🏍️",fr:"Resident Evil",sp:"Resident Evil 2",g:"Survival Horror",ra:"Mensch",ge:"weiblich",h:168,ha:"Rot",w:"Pistole",p:"Spielbar"},
{n:"Solid Snake",e:"🚬",fr:"Metal Gear Solid",sp:"Metal Gear Solid",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Big Boss",e:"🎖️",fr:"Metal Gear Solid",sp:"Metal Gear Solid V: The Phantom Pain",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:182,ha:"Schwarz",w:"Gewehr",p:"Spielbar"},
{n:"Raiden",e:"⚡",fr:"Metal Gear Solid",sp:"Metal Gear Solid 2: Sons of Liberty",g:"Action-Adventure",ra:"Cyborg",ge:"männlich",h:182,ha:"Blond",w:"Katana",p:"Spielbar"},
{n:"Revolver Ocelot",e:"🤠",fr:"Metal Gear Solid",sp:"Metal Gear Solid V: The Phantom Pain",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Weiß",w:"Revolver",p:"NPC"},
{n:"Liquid Snake",e:"🐍",fr:"Metal Gear Solid",sp:"Metal Gear Solid",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Blond",w:"Gewehr",p:"NPC"},
{n:"Ryu",e:"🥋",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Ken Masters",e:"🔥",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:175,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Chun-Li",e:"🦵",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Guile",e:"🇺🇸",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:182,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"M. Bison",e:"👊",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:188,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Akuma",e:"👹",fr:"Street Fighter",sp:"Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:187,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Scorpion",e:"🔥",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ra:"Untoter",ge:"männlich",h:188,ha:"Schwarz",w:"Speer",p:"Spielbar"},
{n:"Sub-Zero",e:"❄️",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Liu Kang",e:"🐉",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Raiden (Mortal Kombat)",e:"⚡",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ra:"Gott",ge:"männlich",h:180,ha:"Weiß",w:"Magie",p:"NPC"},
{n:"Sonya Blade",e:"💥",fr:"Mortal Kombat",sp:"Mortal Kombat 11",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:170,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Master Chief",e:"🪖",fr:"Halo",sp:"Halo: Combat Evolved",g:"FPS",ra:"Mensch",ge:"männlich",h:213,ha:"Keine",w:"Gewehr",p:"Spielbar"},
{n:"Cortana",e:"💠",fr:"Halo",sp:"Halo: Combat Evolved",g:"FPS",ra:"Roboter",ge:"weiblich",h:170,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Arbiter",e:"👽",fr:"Halo",sp:"Halo 2",g:"FPS",ra:"Alien",ge:"männlich",h:230,ha:"Keine",w:"Energieklinge",p:"Spielbar"},
{n:"Geralt of Rivia",e:"⚔️",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:181,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Yennefer of Vengerberg",e:"🔮",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:160,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Triss Merigold",e:"🔥",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:168,ha:"Rot",w:"Magie",p:"NPC"},
{n:"Ciri",e:"⚔️",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:172,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Aloy",e:"🏹",fr:"Horizon",sp:"Horizon Zero Dawn",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:173,ha:"Rot",w:"Bogen",p:"Spielbar"},
{n:"Rost",e:"🏹",fr:"Horizon",sp:"Horizon Zero Dawn",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Bogen",p:"NPC"},
{n:"Sylens",e:"🎭",fr:"Horizon",sp:"Horizon Zero Dawn",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:180,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Wolf",e:"🥷",fr:"Sekiro",sp:"Sekiro: Shadows Die Twice",g:"Souls-like",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Genichiro Ashina",e:"⚡",fr:"Sekiro",sp:"Sekiro: Shadows Die Twice",g:"Souls-like",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Katana",p:"NPC"},
{n:"Der Jäger",e:"🌙",fr:"Bloodborne",sp:"Bloodborne",g:"Souls-like",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Sense",p:"Spielbar"},
{n:"Gehrman",e:"🕯️",fr:"Bloodborne",sp:"Bloodborne",g:"Souls-like",ra:"Mensch",ge:"männlich",h:185,ha:"Grau",w:"Sense",p:"NPC"},
{n:"Lady Maria",e:"🗡️",fr:"Bloodborne",sp:"Bloodborne",g:"Souls-like",ra:"Mensch",ge:"weiblich",h:170,ha:"Weiß",w:"Zwei Schwerter",p:"NPC"},
{n:"Joker",e:"🎭",fr:"Persona",sp:"Persona 5",g:"JRPG",ra:"Mensch",ge:"männlich",h:174,ha:"Schwarz",w:"Dolch",p:"Spielbar"},
{n:"Morgana",e:"🐱",fr:"Persona",sp:"Persona 5",g:"JRPG",ra:"Tier",ge:"männlich",h:50,ha:"Schwarz",w:"Dolch",p:"Spielbar"},
{n:"Ann Takamaki",e:"👠",fr:"Persona",sp:"Persona 5",g:"JRPG",ra:"Mensch",ge:"weiblich",h:160,ha:"Blond",w:"Peitsche",p:"Spielbar"},
{n:"Ryuji Sakamoto",e:"⚡",fr:"Persona",sp:"Persona 5",g:"JRPG",ra:"Mensch",ge:"männlich",h:172,ha:"Blond",w:"Keule",p:"Spielbar"},
{n:"Dante",e:"😈",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ra:"Dämon",ge:"männlich",h:189,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Vergil",e:"⚔️",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ra:"Dämon",ge:"männlich",h:186,ha:"Weiß",w:"Katana",p:"NPC"},
{n:"Nero",e:"🦾",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ra:"Dämon",ge:"männlich",h:180,ha:"Weiß",w:"Schwert",p:"Spielbar"},
{n:"Trish",e:"⚡",fr:"Devil May Cry",sp:"Devil May Cry 5",g:"Hack & Slash",ra:"Dämon",ge:"weiblich",h:175,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Tracer",e:"⏱️",fr:"Overwatch",sp:"Overwatch",g:"FPS",ra:"Mensch",ge:"weiblich",h:163,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Reaper",e:"💀",fr:"Overwatch",sp:"Overwatch",g:"FPS",ra:"Untoter",ge:"männlich",h:195,ha:"Schwarz",w:"Schrotflinte",p:"Spielbar"},
{n:"Widowmaker",e:"🎯",fr:"Overwatch",sp:"Overwatch",g:"FPS",ra:"Mensch",ge:"weiblich",h:180,ha:"Schwarz",w:"Scharfschützengewehr",p:"Spielbar"},
{n:"D.Va",e:"🎮",fr:"Overwatch",sp:"Overwatch",g:"FPS",ra:"Mensch",ge:"weiblich",h:158,ha:"Braun",w:"Mech-Kanonen",p:"Spielbar"},
{n:"Genji",e:"🍃",fr:"Overwatch",sp:"Overwatch",g:"FPS",ra:"Cyborg",ge:"männlich",h:175,ha:"Braun",w:"Katana",p:"Spielbar"},
{n:"Steve",e:"⛏️",fr:"Minecraft",sp:"Minecraft",g:"Open World",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Spitzhacke",p:"Spielbar"},
{n:"Alex",e:"🏹",fr:"Minecraft",sp:"Minecraft",g:"Open World",ra:"Mensch",ge:"weiblich",h:180,ha:"Rot",w:"Bogen",p:"Spielbar"},
{n:"Enderman",e:"🕶️",fr:"Minecraft",sp:"Minecraft",g:"Open World",ra:"Monster",ge:"männlich",h:290,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Creeper",e:"💚",fr:"Minecraft",sp:"Minecraft",g:"Open World",ra:"Monster",ge:"männlich",h:180,ha:"Keine",w:"Explosion",p:"NPC"},
{n:"Carl \"CJ\" Johnson",e:"🎮",fr:"Grand Theft Auto",sp:"Grand Theft Auto: San Andreas",g:"Open World",ra:"Mensch",ge:"männlich",h:183,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Trevor Philips",e:"🔫",fr:"Grand Theft Auto",sp:"Grand Theft Auto V",g:"Open World",ra:"Mensch",ge:"männlich",h:178,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"Michael De Santa",e:"🕶️",fr:"Grand Theft Auto",sp:"Grand Theft Auto V",g:"Open World",ra:"Mensch",ge:"männlich",h:180,ha:"Grau",w:"Pistole",p:"Spielbar"},
{n:"Franklin Clinton",e:"🎧",fr:"Grand Theft Auto",sp:"Grand Theft Auto V",g:"Open World",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Peter Parker",e:"🕷️",fr:"Marvel's Spider-Man",sp:"Marvel's Spider-Man",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Miles Morales",e:"🕸️",fr:"Marvel's Spider-Man",sp:"Marvel's Spider-Man: Miles Morales",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Mary Jane Watson",e:"📰",fr:"Marvel's Spider-Man",sp:"Marvel's Spider-Man",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:168,ha:"Rot",w:"Keine",p:"NPC"},
{n:"Ezio Auditore",e:"🗡️",fr:"Assassin's Creed",sp:"Assassin's Creed II",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Braun",w:"Versteckte Klinge",p:"Spielbar"},
{n:"Altaïr Ibn-La'Ahad",e:"🦅",fr:"Assassin's Creed",sp:"Assassin's Creed",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Versteckte Klinge",p:"Spielbar"},
{n:"Connor Kenway",e:"🏹",fr:"Assassin's Creed",sp:"Assassin's Creed III",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:188,ha:"Schwarz",w:"Tomahawk",p:"Spielbar"},
{n:"Kassandra",e:"⚔️",fr:"Assassin's Creed",sp:"Assassin's Creed Odyssey",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:178,ha:"Schwarz",w:"Speer",p:"Spielbar"},
{n:"V",e:"🤖",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:175,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Johnny Silverhand",e:"🎸",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:183,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Judy Alvarez",e:"🥽",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:163,ha:"Blau",w:"Pistole",p:"NPC"},
{n:"Panam Palmer",e:"🚗",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Braun",w:"Gewehr",p:"NPC"},
{n:"Joel Miller",e:"🎸",fr:"The Last of Us",sp:"The Last of Us",g:"Survival Horror",ra:"Mensch",ge:"männlich",h:188,ha:"Grau",w:"Gewehr",p:"Spielbar"},
{n:"Ellie Williams",e:"🔪",fr:"The Last of Us",sp:"The Last of Us",g:"Survival Horror",ra:"Mensch",ge:"weiblich",h:163,ha:"Braun",w:"Messer",p:"Spielbar"},
{n:"Abby Anderson",e:"💪",fr:"The Last of Us",sp:"The Last of Us Part II",g:"Survival Horror",ra:"Mensch",ge:"weiblich",h:178,ha:"Blond",w:"Gewehr",p:"Spielbar"},
{n:"Bayonetta",e:"💃",fr:"Bayonetta",sp:"Bayonetta",g:"Hack & Slash",ra:"Mensch",ge:"weiblich",h:172,ha:"Schwarz",w:"Pistolen",p:"Spielbar"},
{n:"Jeanne",e:"🕶️",fr:"Bayonetta",sp:"Bayonetta",g:"Hack & Slash",ra:"Mensch",ge:"weiblich",h:172,ha:"Blond",w:"Pistolen",p:"NPC"},
{n:"Sonic the Hedgehog",e:"💨",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ra:"Tier",ge:"männlich",h:100,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Tails",e:"🦊",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ra:"Tier",ge:"männlich",h:80,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Knuckles the Echidna",e:"👊",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ra:"Tier",ge:"männlich",h:107,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Dr. Eggman",e:"🥚",fr:"Sonic the Hedgehog",sp:"Sonic the Hedgehog 2",g:"Platformer",ra:"Mensch",ge:"männlich",h:185,ha:"Keine",w:"Maschinen",p:"NPC"},
{n:"Shadow the Hedgehog",e:"🖤",fr:"Sonic the Hedgehog",sp:"Sonic Adventure 2",g:"Platformer",ra:"Tier",ge:"männlich",h:100,ha:"Keine",w:"Fäuste",p:"Spielbar"},
{n:"Amy Rose",e:"🔨",fr:"Sonic the Hedgehog",sp:"Sonic CD",g:"Platformer",ra:"Tier",ge:"weiblich",h:90,ha:"Keine",w:"Hammer",p:"Spielbar"},
{n:"Mega Man",e:"🤖",fr:"Mega Man",sp:"Mega Man 2",g:"Platformer",ra:"Roboter",ge:"männlich",h:130,ha:"Keine",w:"Blaster",p:"Spielbar"},
{n:"Dr. Wily",e:"🧪",fr:"Mega Man",sp:"Mega Man 2",g:"Platformer",ra:"Mensch",ge:"männlich",h:170,ha:"Weiß",w:"Maschinen",p:"NPC"},
{n:"Roll",e:"🧹",fr:"Mega Man",sp:"Mega Man 2",g:"Platformer",ra:"Roboter",ge:"weiblich",h:125,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Samus Aran",e:"🚀",fr:"Metroid",sp:"Super Metroid",g:"Platformer",ra:"Mensch",ge:"weiblich",h:185,ha:"Blond",w:"Blaster",p:"Spielbar"},
{n:"Deckard Cain",e:"📚",fr:"Diablo",sp:"Diablo II",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:175,ha:"Weiß",w:"Stab",p:"NPC"},
{n:"Lilith",e:"😈",fr:"Diablo",sp:"Diablo IV",g:"Action-RPG",ra:"Dämon",ge:"weiblich",h:180,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Arthur Morgan",e:"🤠",fr:"Red Dead Redemption",sp:"Red Dead Redemption 2",g:"Open World",ra:"Mensch",ge:"männlich",h:183,ha:"Braun",w:"Revolver",p:"Spielbar"},
{n:"John Marston",e:"🐴",fr:"Red Dead Redemption",sp:"Red Dead Redemption",g:"Open World",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Revolver",p:"Spielbar"},
{n:"Dutch van der Linde",e:"🎩",fr:"Red Dead Redemption",sp:"Red Dead Redemption 2",g:"Open World",ra:"Mensch",ge:"männlich",h:178,ha:"Braun",w:"Revolver",p:"NPC"},
{n:"Cuphead",e:"☕",fr:"Cuphead",sp:"Cuphead",g:"Platformer",ra:"Magisches Wesen",ge:"männlich",h:90,ha:"Keine",w:"Finger-Pistole",p:"Spielbar"},
{n:"Mugman",e:"🍶",fr:"Cuphead",sp:"Cuphead",g:"Platformer",ra:"Magisches Wesen",ge:"männlich",h:90,ha:"Keine",w:"Finger-Pistole",p:"Spielbar"},
{n:"King Dice",e:"🎲",fr:"Cuphead",sp:"Cuphead",g:"Platformer",ra:"Magisches Wesen",ge:"männlich",h:175,ha:"Keine",w:"Magie",p:"NPC"},
{n:"The Knight",e:"🗡️",fr:"Hollow Knight",sp:"Hollow Knight",g:"Platformer",ra:"Tier",ge:"männlich",h:60,ha:"Keine",w:"Nagel",p:"Spielbar"},
{n:"Hornet",e:"🕷️",fr:"Hollow Knight",sp:"Hollow Knight",g:"Platformer",ra:"Tier",ge:"weiblich",h:65,ha:"Keine",w:"Nadel",p:"Spielbar"},
{n:"Doom Slayer",e:"😈",fr:"Doom",sp:"Doom Eternal",g:"FPS",ra:"Mensch",ge:"männlich",h:205,ha:"Keine",w:"Gewehr",p:"Spielbar"},
{n:"Ahri",e:"🦊",fr:"League of Legends",sp:"League of Legends",g:"Fighting-Game",ra:"Tier",ge:"weiblich",h:163,ha:"Orange",w:"Magie",p:"Spielbar"},
{n:"Yasuo",e:"⚔️",fr:"League of Legends",sp:"League of Legends",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:183,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Jinx",e:"💥",fr:"League of Legends",sp:"League of Legends",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:175,ha:"Blau",w:"Gewehr",p:"Spielbar"},
{n:"Lux",e:"✨",fr:"League of Legends",sp:"League of Legends",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:169,ha:"Blond",w:"Magie",p:"Spielbar"},
{n:"Garen",e:"⚔️",fr:"League of Legends",sp:"League of Legends",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:193,ha:"Blond",w:"Großschwert",p:"Spielbar"},
{n:"Terra",e:"🌍",fr:"Kingdom Hearts",sp:"Kingdom Hearts: Birth by Sleep",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Aqua",e:"💧",fr:"Kingdom Hearts",sp:"Kingdom Hearts: Birth by Sleep",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Blau",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Xion",e:"🍦",fr:"Kingdom Hearts",sp:"Kingdom Hearts 358/2 Days",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:155,ha:"Schwarz",w:"Schlüsselschwert",p:"Spielbar"},
{n:"Master Xehanort",e:"🌑",fr:"Kingdom Hearts",sp:"Kingdom Hearts: Birth by Sleep",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:185,ha:"Weiß",w:"Schlüsselschwert",p:"NPC"},
{n:"Ripper Roo",e:"🦘",fr:"Crash Bandicoot",sp:"Crash Bandicoot",g:"Platformer",ra:"Tier",ge:"männlich",h:90,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Dr. N. Gin",e:"🤖",fr:"Crash Bandicoot",sp:"Crash Bandicoot 2: Cortex Strikes Back",g:"Platformer",ra:"Mensch",ge:"männlich",h:175,ha:"Keine",w:"Maschinen",p:"NPC"},
{n:"N. Tropy",e:"⏳",fr:"Crash Bandicoot",sp:"Crash Bandicoot: Warped",g:"Platformer",ra:"Mensch",ge:"männlich",h:190,ha:"Weiß",w:"Magie",p:"NPC"},
{n:"Nina Cortex",e:"🖤",fr:"Crash Bandicoot",sp:"Crash Twinsanity",g:"Platformer",ra:"Mensch",ge:"weiblich",h:150,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Sam Nishimura",e:"📷",fr:"Tomb Raider",sp:"Tomb Raider (2013)",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Ana",e:"🗡️",fr:"Tomb Raider",sp:"Rise of the Tomb Raider",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:170,ha:"Braun",w:"Pistole",p:"NPC"},
{n:"Jacob",e:"🏹",fr:"Tomb Raider",sp:"Rise of the Tomb Raider",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Grau",w:"Bogen",p:"NPC"},
{n:"Yhorm the Giant",e:"🗿",fr:"Dark Souls",sp:"Dark Souls III",g:"Souls-like",ra:"Riese",ge:"männlich",h:350,ha:"Keine",w:"Großschwert",p:"NPC"},
{n:"Vordt of the Boreal Valley",e:"❄️",fr:"Dark Souls",sp:"Dark Souls III",g:"Souls-like",ra:"Monster",ge:"männlich",h:250,ha:"Weiß",w:"Keule",p:"NPC"},
{n:"Nashandra",e:"👑",fr:"Dark Souls",sp:"Dark Souls II",g:"Souls-like",ra:"Dämon",ge:"weiblich",h:175,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Messmer the Impaler",e:"🔥",fr:"Elden Ring",sp:"Elden Ring: Shadow of the Erdtree",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:210,ha:"Rot",w:"Speer",p:"NPC"},
{n:"Miquella",e:"😇",fr:"Elden Ring",sp:"Elden Ring: Shadow of the Erdtree",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:150,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Cammy White",e:"🎯",fr:"Street Fighter",sp:"Super Street Fighter II",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:169,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Juri Han",e:"🦵",fr:"Street Fighter",sp:"Street Fighter IV",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:170,ha:"Orange",w:"Fäuste",p:"Spielbar"},
{n:"Luke",e:"🥊",fr:"Street Fighter",sp:"Street Fighter 6",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:183,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Kitana",e:"🪭",fr:"Mortal Kombat",sp:"Mortal Kombat 1",g:"Fighting-Game",ra:"Mensch",ge:"weiblich",h:170,ha:"Schwarz",w:"Fächer",p:"Spielbar"},
{n:"Kung Lao",e:"🎩",fr:"Mortal Kombat",sp:"Mortal Kombat X",g:"Fighting-Game",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Wurfhut",p:"Spielbar"},
{n:"Shao Kahn",e:"💀",fr:"Mortal Kombat",sp:"Mortal Kombat 9",g:"Fighting-Game",ra:"Gott",ge:"männlich",h:240,ha:"Keine",w:"Hammer",p:"NPC"},
{n:"Vesemir",e:"🧙",fr:"The Witcher",sp:"The Witcher",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:175,ha:"Weiß",w:"Schwert",p:"NPC"},
{n:"Letho",e:"⚔️",fr:"The Witcher",sp:"The Witcher 2: Assassins of Kings",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:190,ha:"Keine",w:"Schwert",p:"NPC"},
{n:"Dandelion",e:"🎻",fr:"The Witcher",sp:"The Witcher 2: Assassins of Kings",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:178,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Nil",e:"🗡️",fr:"Horizon",sp:"Horizon Forbidden West",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Speer",p:"NPC"},
{n:"Regalla",e:"🪓",fr:"Horizon",sp:"Horizon Forbidden West",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:170,ha:"Rot",w:"Axt",p:"NPC"},
{n:"Ludwig, the Accursed",e:"⚔️",fr:"Bloodborne",sp:"Bloodborne: The Old Hunters",g:"Souls-like",ra:"Monster",ge:"männlich",h:220,ha:"Weiß",w:"Großschwert",p:"NPC"},
{n:"Yu Narukami",e:"🗡️",fr:"Persona",sp:"Persona 4",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Grau",w:"Schwert",p:"Spielbar"},
{n:"Chie Satonaka",e:"🥋",fr:"Persona",sp:"Persona 4",g:"JRPG",ra:"Mensch",ge:"weiblich",h:158,ha:"Braun",w:"Fäuste",p:"Spielbar"},
{n:"Makoto Yuki",e:"🔫",fr:"Persona",sp:"Persona 3",g:"JRPG",ra:"Mensch",ge:"männlich",h:174,ha:"Blau",w:"Pistole",p:"Spielbar"},
{n:"Lady",e:"🔫",fr:"Devil May Cry",sp:"Devil May Cry 4",g:"Hack & Slash",ra:"Mensch",ge:"weiblich",h:168,ha:"Braun",w:"Gewehr",p:"NPC"},
{n:"Lucia",e:"🗡️",fr:"Devil May Cry",sp:"Devil May Cry 2",g:"Hack & Slash",ra:"Mensch",ge:"weiblich",h:170,ha:"Braun",w:"Dolche",p:"Spielbar"},
{n:"Kiriko",e:"🦊",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ra:"Mensch",ge:"weiblich",h:160,ha:"Schwarz",w:"Dolch",p:"Spielbar"},
{n:"Sojourn",e:"🔫",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ra:"Mensch",ge:"weiblich",h:180,ha:"Grau",w:"Gewehr",p:"Spielbar"},
{n:"Junker Queen",e:"🪓",fr:"Overwatch",sp:"Overwatch 2",g:"FPS",ra:"Mensch",ge:"weiblich",h:190,ha:"Rot",w:"Axt",p:"Spielbar"},
{n:"Arch-Illager",e:"👹",fr:"Minecraft",sp:"Minecraft Dungeons",g:"Action-RPG",ra:"Monster",ge:"männlich",h:120,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Solomon Reed",e:"🕶️",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077: Phantom Liberty",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:180,ha:"Grau",w:"Pistole",p:"NPC"},
{n:"Songbird",e:"🎤",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077: Phantom Liberty",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Loki",e:"🐺",fr:"Bayonetta",sp:"Bayonetta 2",g:"Hack & Slash",ra:"Mensch",ge:"männlich",h:140,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Viola",e:"🐈",fr:"Bayonetta",sp:"Bayonetta 3",g:"Hack & Slash",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"X",e:"🔵",fr:"Mega Man",sp:"Mega Man X",g:"Platformer",ra:"Roboter",ge:"männlich",h:130,ha:"Blau",w:"Blaster",p:"Spielbar"},
{n:"Zero",e:"🔴",fr:"Mega Man",sp:"Mega Man X",g:"Platformer",ra:"Roboter",ge:"männlich",h:165,ha:"Rot",w:"Schwert",p:"Spielbar"},
{n:"Ridley",e:"🐉",fr:"Metroid",sp:"Metroid Prime",g:"Platformer",ra:"Alien",ge:"männlich",h:500,ha:"Keine",w:"Klauen",p:"NPC"},
{n:"Raven Beak",e:"🦅",fr:"Metroid",sp:"Metroid Dread",g:"Platformer",ra:"Alien",ge:"männlich",h:220,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Ms. Chalice",e:"👻",fr:"Cuphead",sp:"Cuphead: The Delicious Last Course",g:"Platformer",ra:"Magisches Wesen",ge:"weiblich",h:90,ha:"Keine",w:"Finger-Pistole",p:"Spielbar"},
{n:"Lace",e:"🪡",fr:"Hollow Knight",sp:"Hollow Knight: Silksong",g:"Platformer",ra:"Tier",ge:"weiblich",h:70,ha:"Keine",w:"Degen",p:"NPC"},
{n:"Samuel Hayden",e:"🤖",fr:"Doom",sp:"Doom (2016)",g:"FPS",ra:"Roboter",ge:"männlich",h:190,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Krieger des Lichts",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Garland",e:"🛡️",fr:"Final Fantasy",sp:"Final Fantasy",g:"JRPG",ra:"Mensch",ge:"männlich",h:200,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Prinzessin Sarah",e:"👸",fr:"Final Fantasy",sp:"Final Fantasy",g:"JRPG",ra:"Mensch",ge:"weiblich",h:160,ha:"Blond",w:"Keine",p:"NPC"},
{n:"Chaos",e:"😈",fr:"Final Fantasy",sp:"Final Fantasy",g:"JRPG",ra:"Dämon",ge:"männlich",h:220,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Bahamut",e:"🐉",fr:"Final Fantasy",sp:"Final Fantasy",g:"JRPG",ra:"Drache",ge:"männlich",h:300,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Firion",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy II",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Maria (Final Fantasy II)",e:"🏹",fr:"Final Fantasy",sp:"Final Fantasy II",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Braun",w:"Bogen",p:"Spielbar"},
{n:"Guy",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy II",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Fäuste",p:"Spielbar"},
{n:"Leon",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy II",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Kaiser Mateus",e:"👑",fr:"Final Fantasy",sp:"Final Fantasy II",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Luneth",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy III",g:"JRPG",ra:"Mensch",ge:"männlich",h:160,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Arc",e:"📖",fr:"Final Fantasy",sp:"Final Fantasy III",g:"JRPG",ra:"Mensch",ge:"männlich",h:155,ha:"Blau",w:"Magie",p:"Spielbar"},
{n:"Refia",e:"🔨",fr:"Final Fantasy",sp:"Final Fantasy III",g:"JRPG",ra:"Mensch",ge:"weiblich",h:158,ha:"Rot",w:"Hammer",p:"Spielbar"},
{n:"Ingus",e:"🛡️",fr:"Final Fantasy",sp:"Final Fantasy III",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Xande",e:"😈",fr:"Final Fantasy",sp:"Final Fantasy III",g:"JRPG",ra:"Mensch",ge:"männlich",h:190,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Cecil Harvey",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy IV",g:"JRPG",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Schwert",p:"Spielbar"},
{n:"Kain Highwind",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy IV",g:"JRPG",ra:"Mensch",ge:"männlich",h:195,ha:"Schwarz",w:"Speer",p:"Spielbar"},
{n:"Rosa Farrell",e:"🏹",fr:"Final Fantasy",sp:"Final Fantasy IV",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Blond",w:"Bogen",p:"Spielbar"},
{n:"Rydia",e:"🐉",fr:"Final Fantasy",sp:"Final Fantasy IV",g:"JRPG",ra:"Mensch",ge:"weiblich",h:155,ha:"Grün",w:"Magie",p:"Spielbar"},
{n:"Golbez",e:"🌑",fr:"Final Fantasy",sp:"Final Fantasy IV",g:"JRPG",ra:"Mensch",ge:"männlich",h:200,ha:"Blau",w:"Magie",p:"NPC"},
{n:"Edge Geraldine",e:"🥷",fr:"Final Fantasy",sp:"Final Fantasy IV",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Weiß",w:"Shuriken",p:"Spielbar"},
{n:"Bartz Klauser",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy V",g:"JRPG",ra:"Mensch",ge:"männlich",h:175,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Lenna Tycoon",e:"👸",fr:"Final Fantasy",sp:"Final Fantasy V",g:"JRPG",ra:"Mensch",ge:"weiblich",h:160,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Galuf Halm Baldesion",e:"👴",fr:"Final Fantasy",sp:"Final Fantasy V",g:"JRPG",ra:"Mensch",ge:"männlich",h:170,ha:"Weiß",w:"Fäuste",p:"Spielbar"},
{n:"Faris Scherwiz",e:"🏴‍☠️",fr:"Final Fantasy",sp:"Final Fantasy V",g:"JRPG",ra:"Mensch",ge:"weiblich",h:168,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Exdeath",e:"🌳",fr:"Final Fantasy",sp:"Final Fantasy V",g:"JRPG",ra:"Monster",ge:"männlich",h:210,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Terra Branford",e:"🌿",fr:"Final Fantasy",sp:"Final Fantasy VI",g:"JRPG",ra:"Magisches Wesen",ge:"weiblich",h:163,ha:"Grün",w:"Magie",p:"Spielbar"},
{n:"Locke Cole",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy VI",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Rot",w:"Dolch",p:"Spielbar"},
{n:"Celes Chere",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy VI",g:"JRPG",ra:"Mensch",ge:"weiblich",h:167,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Kefka Palazzo",e:"🤡",fr:"Final Fantasy",sp:"Final Fantasy VI",g:"JRPG",ra:"Mensch",ge:"männlich",h:178,ha:"Orange",w:"Magie",p:"NPC"},
{n:"Edgar Roni Figaro",e:"🔧",fr:"Final Fantasy",sp:"Final Fantasy VI",g:"JRPG",ra:"Mensch",ge:"männlich",h:183,ha:"Blond",w:"Gewehr",p:"Spielbar"},
{n:"Sabin Rene Figaro",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy VI",g:"JRPG",ra:"Mensch",ge:"männlich",h:188,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Vaan",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy XII",g:"JRPG",ra:"Mensch",ge:"männlich",h:172,ha:"Blond",w:"Schwert",p:"Spielbar"},
{n:"Ashe",e:"👸",fr:"Final Fantasy",sp:"Final Fantasy XII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:165,ha:"Silber",w:"Schwert",p:"Spielbar"},
{n:"Balthier",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy XII",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Pistole",p:"Spielbar"},
{n:"Fran",e:"🏹",fr:"Final Fantasy",sp:"Final Fantasy XII",g:"JRPG",ra:"Tier",ge:"weiblich",h:190,ha:"Weiß",w:"Bogen",p:"Spielbar"},
{n:"Basch fon Ronsenburg",e:"🛡️",fr:"Final Fantasy",sp:"Final Fantasy XII",g:"JRPG",ra:"Mensch",ge:"männlich",h:188,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Vayne Solidor",e:"👑",fr:"Final Fantasy",sp:"Final Fantasy XII",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Lightning",e:"⚔️",fr:"Final Fantasy",sp:"Final Fantasy XIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:170,ha:"Rosa",w:"Schwert",p:"Spielbar"},
{n:"Snow Villiers",e:"👊",fr:"Final Fantasy",sp:"Final Fantasy XIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:190,ha:"Blond",w:"Fäuste",p:"Spielbar"},
{n:"Sazh Katzroy",e:"🔫",fr:"Final Fantasy",sp:"Final Fantasy XIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Pistole",p:"Spielbar"},
{n:"Oerba Dia Vanille",e:"🌸",fr:"Final Fantasy",sp:"Final Fantasy XIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:158,ha:"Rot",w:"Speer",p:"Spielbar"},
{n:"Hope Estheim",e:"🔨",fr:"Final Fantasy",sp:"Final Fantasy XIII",g:"JRPG",ra:"Mensch",ge:"männlich",h:158,ha:"Silber",w:"Keule",p:"Spielbar"},
{n:"Oerba Yun Fang",e:"🗡️",fr:"Final Fantasy",sp:"Final Fantasy XIII",g:"JRPG",ra:"Mensch",ge:"weiblich",h:172,ha:"Schwarz",w:"Speer",p:"Spielbar"},
{n:"Skull Kid",e:"🎭",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Majora's Mask",g:"Action-Adventure",ra:"Magisches Wesen",ge:"männlich",h:100,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Anju",e:"🐔",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Majora's Mask",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:160,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Kafei",e:"🗝️",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Majora's Mask",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:60,ha:"Blau",w:"Keine",p:"NPC"},
{n:"Tatl",e:"✨",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Majora's Mask",g:"Action-Adventure",ra:"Fee",ge:"weiblich",h:10,ha:"Gelb",w:"Magie",p:"NPC"},
{n:"Majora",e:"👹",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Majora's Mask",g:"Action-Adventure",ra:"Dämon",ge:"männlich",h:150,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Groose",e:"🐓",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Skyward Sword",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:185,ha:"Rot",w:"Fäuste",p:"NPC"},
{n:"Fi",e:"💠",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Skyward Sword",g:"Action-Adventure",ra:"Magisches Wesen",ge:"weiblich",h:170,ha:"Blau",w:"Keine",p:"NPC"},
{n:"Ghirahim",e:"🗡️",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Skyward Sword",g:"Action-Adventure",ra:"Dämon",ge:"männlich",h:190,ha:"Weiß",w:"Schwert",p:"NPC"},
{n:"Demise",e:"😈",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Skyward Sword",g:"Action-Adventure",ra:"Dämon",ge:"männlich",h:220,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Gaepora",e:"🦉",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Skyward Sword",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Grau",w:"Keine",p:"NPC"},
{n:"Spyro",e:"🐲",fr:"Spyro the Dragon",sp:"Spyro the Dragon",g:"Platformer",ra:"Drache",ge:"männlich",h:60,ha:"Lila",w:"Feueratem",p:"Spielbar"},
{n:"Sparx",e:"🐝",fr:"Spyro the Dragon",sp:"Spyro the Dragon",g:"Platformer",ra:"Tier",ge:"männlich",h:10,ha:"Gelb",w:"Keine",p:"NPC"},
{n:"Gnasty Gnorc",e:"👹",fr:"Spyro the Dragon",sp:"Spyro the Dragon",g:"Platformer",ra:"Monster",ge:"männlich",h:150,ha:"Grün",w:"Keule",p:"NPC"},
{n:"Elora",e:"🦌",fr:"Spyro the Dragon",sp:"Spyro the Dragon",g:"Platformer",ra:"Tier",ge:"weiblich",h:165,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Hunter",e:"🐆",fr:"Spyro the Dragon",sp:"Spyro the Dragon",g:"Platformer",ra:"Tier",ge:"männlich",h:175,ha:"Gelb",w:"Bogen",p:"NPC"},
{n:"Fox McCloud",e:"🦊",fr:"Star Fox",sp:"Star Fox 64",g:"FPS",ra:"Tier",ge:"männlich",h:100,ha:"Braun",w:"Blaster",p:"Spielbar"},
{n:"Falco Lombardi",e:"🦅",fr:"Star Fox",sp:"Star Fox 64",g:"FPS",ra:"Tier",ge:"männlich",h:100,ha:"Blau",w:"Blaster",p:"Spielbar"},
{n:"Peppy Hare",e:"🐰",fr:"Star Fox",sp:"Star Fox 64",g:"FPS",ra:"Tier",ge:"männlich",h:100,ha:"Grau",w:"Blaster",p:"Spielbar"},
{n:"Slippy Toad",e:"🐸",fr:"Star Fox",sp:"Star Fox 64",g:"FPS",ra:"Tier",ge:"männlich",h:90,ha:"Grün",w:"Blaster",p:"Spielbar"},
{n:"Andross",e:"👹",fr:"Star Fox",sp:"Star Fox 64",g:"FPS",ra:"Monster",ge:"männlich",h:250,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Cal Kestis",e:"⚔️",fr:"Star Wars",sp:"Star Wars Jedi: Fallen Order",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Braun",w:"Lichtschwert",p:"Spielbar"},
{n:"Cere Junda",e:"🗡️",fr:"Star Wars",sp:"Star Wars Jedi: Fallen Order",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:170,ha:"Schwarz",w:"Lichtschwert",p:"NPC"},
{n:"Greez Dritus",e:"🚀",fr:"Star Wars",sp:"Star Wars Jedi: Fallen Order",g:"Action-Adventure",ra:"Alien",ge:"männlich",h:140,ha:"Keine",w:"Pistole",p:"NPC"},
{n:"Trilla Suduri",e:"😈",fr:"Star Wars",sp:"Star Wars Jedi: Fallen Order",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:175,ha:"Keine",w:"Lichtschwert",p:"NPC"},
{n:"Merrin",e:"🔮",fr:"Star Wars",sp:"Star Wars Jedi: Fallen Order",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:168,ha:"Schwarz",w:"Magie",p:"NPC"},
{n:"Starkiller",e:"⚡",fr:"Star Wars",sp:"Star Wars: The Force Unleashed",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Lichtschwert",p:"Spielbar"},
{n:"Darth Vader",e:"🖤",fr:"Star Wars",sp:"Star Wars: The Force Unleashed",g:"Action-Adventure",ra:"Cyborg",ge:"männlich",h:202,ha:"Keine",w:"Lichtschwert",p:"NPC"},
{n:"General Rahm Kota",e:"🕶️",fr:"Star Wars",sp:"Star Wars: The Force Unleashed",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:190,ha:"Grau",w:"Lichtschwert",p:"NPC"},
{n:"Juno Eclipse",e:"🚀",fr:"Star Wars",sp:"Star Wars: The Force Unleashed",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:170,ha:"Schwarz",w:"Pistole",p:"NPC"},
{n:"Imperator Palpatine",e:"⚡",fr:"Star Wars",sp:"Star Wars: The Force Unleashed",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:170,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Captain Price",e:"🎖️",fr:"Call of Duty",sp:"Call of Duty: Modern Warfare",g:"FPS",ra:"Mensch",ge:"männlich",h:185,ha:"Braun",w:"Gewehr",p:"Spielbar"},
{n:"John \"Soap\" MacTavish",e:"🪖",fr:"Call of Duty",sp:"Call of Duty: Modern Warfare",g:"FPS",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Gewehr",p:"Spielbar"},
{n:"Simon \"Ghost\" Riley",e:"💀",fr:"Call of Duty",sp:"Call of Duty: Modern Warfare",g:"FPS",ra:"Mensch",ge:"männlich",h:188,ha:"Schwarz",w:"Gewehr",p:"Spielbar"},
{n:"Vladimir Makarov",e:"😠",fr:"Call of Duty",sp:"Call of Duty: Modern Warfare",g:"FPS",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Gewehr",p:"NPC"},
{n:"Gaz",e:"🎯",fr:"Call of Duty",sp:"Call of Duty: Modern Warfare",g:"FPS",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Gewehr",p:"NPC"},
{n:"Drachenblut",e:"🐲",fr:"The Elder Scrolls",sp:"The Elder Scrolls V: Skyrim",g:"Open World",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Lydia",e:"🛡️",fr:"The Elder Scrolls",sp:"The Elder Scrolls V: Skyrim",g:"Open World",ra:"Mensch",ge:"weiblich",h:170,ha:"Braun",w:"Schwert",p:"NPC"},
{n:"Ulfric Stormcloak",e:"👑",fr:"The Elder Scrolls",sp:"The Elder Scrolls V: Skyrim",g:"Open World",ra:"Mensch",ge:"männlich",h:190,ha:"Blond",w:"Schwert",p:"NPC"},
{n:"Delphine",e:"🗡️",fr:"The Elder Scrolls",sp:"The Elder Scrolls V: Skyrim",g:"Open World",ra:"Mensch",ge:"weiblich",h:168,ha:"Braun",w:"Schwert",p:"NPC"},
{n:"Paarthurnax",e:"🐉",fr:"The Elder Scrolls",sp:"The Elder Scrolls V: Skyrim",g:"Open World",ra:"Drache",ge:"männlich",h:400,ha:"Keine",w:"Feueratem",p:"NPC"},
{n:"Inquisitor",e:"⚔️",fr:"Dragon Age",sp:"Dragon Age: Inquisition",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Schwert",p:"Spielbar"},
{n:"Cassandra Pentaghast",e:"🛡️",fr:"Dragon Age",sp:"Dragon Age: Inquisition",g:"Action-RPG",ra:"Mensch",ge:"weiblich",h:175,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Varric Tethras",e:"🏹",fr:"Dragon Age",sp:"Dragon Age: Inquisition",g:"Action-RPG",ra:"Zwerg",ge:"männlich",h:155,ha:"Braun",w:"Armbrust",p:"NPC"},
{n:"Solas",e:"🔮",fr:"Dragon Age",sp:"Dragon Age: Inquisition",g:"Action-RPG",ra:"Elf",ge:"männlich",h:178,ha:"Keine",w:"Magie",p:"NPC"},
{n:"The Iron Bull",e:"🐂",fr:"Dragon Age",sp:"Dragon Age: Inquisition",g:"Action-RPG",ra:"Ork",ge:"männlich",h:210,ha:"Keine",w:"Axt",p:"NPC"},
{n:"Guide",e:"📖",fr:"Terraria",sp:"Terraria",g:"Open World",ra:"Mensch",ge:"männlich",h:175,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Nurse",e:"➕",fr:"Terraria",sp:"Terraria",g:"Open World",ra:"Mensch",ge:"weiblich",h:165,ha:"Rot",w:"Keine",p:"NPC"},
{n:"Merchant",e:"💰",fr:"Terraria",sp:"Terraria",g:"Open World",ra:"Mensch",ge:"männlich",h:170,ha:"Braun",w:"Keine",p:"NPC"},
{n:"Skeletron",e:"💀",fr:"Terraria",sp:"Terraria",g:"Open World",ra:"Untoter",ge:"männlich",h:300,ha:"Keine",w:"Sense",p:"NPC"},
{n:"Wall of Flesh",e:"👹",fr:"Terraria",sp:"Terraria",g:"Open World",ra:"Monster",ge:"männlich",h:500,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Jin Sakai",e:"⚔️",fr:"Ghost",sp:"Ghost of Tsushima",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Lord Shimura",e:"🎌",fr:"Ghost",sp:"Ghost of Tsushima",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:182,ha:"Grau",w:"Katana",p:"NPC"},
{n:"Yuna",e:"🏹",fr:"Ghost",sp:"Ghost of Tsushima",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Bogen",p:"NPC"},
{n:"Khotun Khan",e:"🐴",fr:"Ghost",sp:"Ghost of Tsushima",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:190,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Lady Masako",e:"🗡️",fr:"Ghost",sp:"Ghost of Tsushima",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:168,ha:"Schwarz",w:"Katana",p:"NPC"},
{n:"Odin",e:"⚡",fr:"God of War",sp:"God of War Ragnarök",g:"Action-Adventure",ra:"Gott",ge:"männlich",h:195,ha:"Grau",w:"Speer",p:"NPC"},
{n:"Thor",e:"🔨",fr:"God of War",sp:"God of War Ragnarök",g:"Action-Adventure",ra:"Gott",ge:"männlich",h:200,ha:"Rot",w:"Hammer",p:"NPC"},
{n:"Rafe Adler",e:"💰",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:185,ha:"Blond",w:"Pistole",p:"NPC"},
{n:"Nadine Ross",e:"🥊",fr:"Uncharted",sp:"Uncharted 4: A Thief's End",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:175,ha:"Schwarz",w:"Fäuste",p:"NPC"},
{n:"Zant",e:"👹",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Twilight Princess",g:"Action-Adventure",ra:"Magisches Wesen",ge:"männlich",h:195,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Great Deku Tree",e:"🌳",fr:"The Legend of Zelda",sp:"The Legend of Zelda: Ocarina of Time",g:"Action-Adventure",ra:"Magisches Wesen",ge:"männlich",h:500,ha:"Keine",w:"Keine",p:"NPC"},
{n:"William Birkin",e:"🧬",fr:"Resident Evil",sp:"Resident Evil 2",g:"Survival Horror",ra:"Monster",ge:"männlich",h:300,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Mr. X",e:"🕴️",fr:"Resident Evil",sp:"Resident Evil 2",g:"Survival Horror",ra:"Monster",ge:"männlich",h:250,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"Emhyr var Emreis",e:"👑",fr:"The Witcher",sp:"The Witcher 3: Wild Hunt",g:"Action-RPG",ra:"Mensch",ge:"männlich",h:180,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Gravemind",e:"🧠",fr:"Halo",sp:"Halo 2",g:"FPS",ra:"Monster",ge:"männlich",h:500,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"343 Guilty Spark",e:"💡",fr:"Halo",sp:"Halo: Combat Evolved",g:"FPS",ra:"Roboter",ge:"männlich",h:50,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Mohg, the Omen",e:"🩸",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:230,ha:"Rot",w:"Speer",p:"NPC"},
{n:"Ornstein",e:"🗡️",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Mensch",ge:"männlich",h:210,ha:"Blond",w:"Speer",p:"NPC"},
{n:"Smough",e:"🔨",fr:"Dark Souls",sp:"Dark Souls",g:"Souls-like",ra:"Mensch",ge:"männlich",h:280,ha:"Keine",w:"Hammer",p:"NPC"},
{n:"Igor",e:"🎩",fr:"Persona",sp:"Persona 5",g:"JRPG",ra:"Magisches Wesen",ge:"männlich",h:190,ha:"Keine",w:"Keine",p:"NPC"},
{n:"Psycho Mantis",e:"🎭",fr:"Metal Gear Solid",sp:"Metal Gear Solid",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Big Smoke",e:"🍔",fr:"Grand Theft Auto",sp:"Grand Theft Auto: San Andreas",g:"Open World",ra:"Mensch",ge:"männlich",h:195,ha:"Keine",w:"Gewehr",p:"NPC"},
{n:"Tyrael",e:"⚖️",fr:"Diablo",sp:"Diablo IV",g:"Action-RPG",ra:"Engel",ge:"männlich",h:220,ha:"Keine",w:"Schwert",p:"NPC"},
{n:"Mephisto",e:"😈",fr:"Diablo",sp:"Diablo II",g:"Action-RPG",ra:"Dämon",ge:"männlich",h:250,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Adam Smasher",e:"🤖",fr:"Cyberpunk 2077",sp:"Cyberpunk 2077",g:"Action-RPG",ra:"Cyborg",ge:"männlich",h:220,ha:"Keine",w:"Fäuste",p:"NPC"},
{n:"David",e:"🔪",fr:"The Last of Us",sp:"The Last of Us",g:"Survival Horror",ra:"Mensch",ge:"männlich",h:180,ha:"Grau",w:"Keine",p:"NPC"},
{n:"Desmond Miles",e:"🗡️",fr:"Assassin's Creed",sp:"Assassin's Creed",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:180,ha:"Braun",w:"Versteckte Klinge",p:"Spielbar"},
{n:"Atsu",e:"🗡️",fr:"Ghost",sp:"Ghost of Yotei",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Katana",p:"Spielbar"},
{n:"Jubei Kitamori",e:"🏹",fr:"Ghost",sp:"Ghost of Yotei",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:178,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Saito",e:"👹",fr:"Ghost",sp:"Ghost of Yotei",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:185,ha:"Schwarz",w:"Katana",p:"NPC"},
{n:"Der Oni",e:"🗿",fr:"Ghost",sp:"Ghost of Yotei",g:"Action-Adventure",ra:"Mensch",ge:"männlich",h:200,ha:"Keine",w:"Großschwert",p:"NPC"},
{n:"Die Kitsune",e:"🦊",fr:"Ghost",sp:"Ghost of Yotei",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Dolch",p:"NPC"},
{n:"Oyuki",e:"🌸",fr:"Ghost",sp:"Ghost of Yotei",g:"Action-Adventure",ra:"Mensch",ge:"weiblich",h:160,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Godfrey, Erster Eldenlord",e:"👑",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:220,ha:"Braun",w:"Axt",p:"NPC"},
{n:"Radagon",e:"☀️",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Gott",ge:"männlich",h:210,ha:"Gold",w:"Hammer",p:"NPC"},
{n:"Rennala, Königin des Vollmonds",e:"🌙",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"weiblich",h:165,ha:"Blond",w:"Magie",p:"NPC"},
{n:"Rykard, Lord der Blasphemie",e:"🐍",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:280,ha:"Rot",w:"Schwert",p:"NPC"},
{n:"Morgott, der Omenkönig",e:"👑",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:230,ha:"Rot",w:"Schwert",p:"NPC"},
{n:"Margit, der Gefallene Omen",e:"🦴",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:230,ha:"Keine",w:"Keule",p:"NPC"},
{n:"Maliketh, die Schwarze Klinge",e:"⚫",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Halbgott",ge:"männlich",h:200,ha:"Schwarz",w:"Schwert",p:"NPC"},
{n:"Astel, Naturgeborener der Leere",e:"🌌",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Alien",ge:"männlich",h:300,ha:"Keine",w:"Magie",p:"NPC"},
{n:"Blaidd, der Halbwolf",e:"🐺",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Monster",ge:"männlich",h:190,ha:"Grau",w:"Schwert",p:"NPC"},
{n:"Iji",e:"🔧",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Riese",ge:"männlich",h:250,ha:"Keine",w:"Armbrust",p:"NPC"},
{n:"Patches, der Entfesselte",e:"🗡️",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Mensch",ge:"männlich",h:175,ha:"Braun",w:"Dolch",p:"NPC"},
{n:"Gideon Ofnir, der Allwissende",e:"📜",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Mensch",ge:"männlich",h:180,ha:"Weiß",w:"Keine",p:"NPC"},
{n:"Fia, die Totenbett-Gefährtin",e:"🖤",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Mensch",ge:"weiblich",h:165,ha:"Schwarz",w:"Keine",p:"NPC"},
{n:"Der Kotfresser",e:"⛓️",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Mensch",ge:"männlich",h:185,ha:"Keine",w:"Schwert",p:"NPC"},
{n:"Alexander, der Kriegertopf",e:"🏺",fr:"Elden Ring",sp:"Elden Ring",g:"Souls-like",ra:"Monster",ge:"männlich",h:200,ha:"Keine",w:"Keule",p:"NPC"},
{n:"Kimahri Ronso",e:"🐯",fr:"Final Fantasy",sp:"Final Fantasy X",g:"JRPG",ra:"Tier",ge:"männlich",h:220,ha:"Blau",w:"Speer",p:"Spielbar"}
];
